### ISSUE TITLE
/resolve-within returns error in cases where there is not a single higher-level concept.

### ISSUE THREAD

**Issue by zednis** [tetherless-world/dtdi-geologic-time-resolver#3]
> for certain period, e.g. those intersects with both Phanerozoic and Precambrian, /resolve-within  will return an error message:
> http://127.0.0.1:5000/resolve-within?min=540&max=542
> This is because there is not another higher concept above Precambrian. Actually Phanerozoic is at the Eon level, and Precambrian is at the ‘super-Eon’ level.

Reported by @xgmachina

**Comment by zednis** [comment]
@xgmachina what would you expect the behavior here to be?  Should it return both Phanerozioc and Precambrian?

**Comment by zednis** [comment]
@xgmachina I have a fix tested in the code that will cause this condition to return an empty set, but I am not sure if this is the desired output.

**Comment by xgmachina** [comment]
return an empty set is a reasonable choice here.

**Comment by zednis** [comment]
Closed by #5
